In [20]:
import tensorflow as tf
import numpy as np

arrayX= [12.4 , 13.5 , 18.7 , 12.8]
x = tf.constant(arrayX)
sect=tf.Session()
print(sect.run(x))
arrayY= [18.8 , 12.4 , 20.5 , 29.9]
y = tf.constant(arrayY)
sect=tf.Session()
print(sect.run(y))

n=len(arrayX)
print("size of array:",n)

m1,v1 = tf.nn.moments(x, axes=[0])  ##mean and varience of X
m2,v2 = tf.nn.moments(y, axes=[0])  ##mean and varience of Y

xi=tf.subtract(x,m1)                ##to find xi
yi=tf.subtract(y,m1)                ##to find yi


p=tf.multiply(t1,t2)               ##multiply  xi and yi


sum1=tf.reduce_sum(M)              ##for calculating covarience
c1=tf.divide(sum1,n)


slope1= tf.divide(covar,v1)         ##m=covariance(x,y)/variance(x) ##to calculate slope


                                        
c1=tf.multiply(m,m1)                ##c=mean(y)−m∗mean(x) 
c=tf.subtract(m2,c1)

with tf.Session() as sect:
    m1=sect.run(m1)
    v1=sect.run(v1)
    m2=sect.run(m2)
    v2=sect.run(v2)
    print("mean of X is:",m1)
    print("varience of X:",v1)
    print("mean  of Y is:",m2)
    print("varience of Y :",v2)
    t1=sect.run(xi)                 ## xi function call
    print(t1)
    t2=sect.run(yi)                 ## yi function call
    print(t2)
    M=sect.run(p)                  ##product of xi and yi array
    print(M)
    covar=sect.run(c1)
    print("covarience is:",covar)      ##slope call  
    m=sect.run(slope1)
    print("slope is:",m)
    
    C=sect.run(c)
    print("intercepts is:",C)
    
    writer = tf.summary.FileWriter("/tmp/tboard/output_HW_1",sect.graph)
    writer.close()

[ 12.39999962  13.5         18.70000076  12.80000019]
[ 18.79999924  12.39999962  20.5         29.89999962]
size of array: 4
mean of X is: 14.35
varience of X: 6.4625
mean  of Y is: 20.4
varience of Y : 39.205
[-1.95000076 -0.85000038  4.35000038 -1.55000019]
[  4.44999886  -1.95000076   6.14999962  15.54999924]
[ -8.67750072   1.65750134  26.75250053 -24.10250092]
covarience is: -5.38671
slope is: -0.375381
intercepts is: 25.7867


In [29]:
import tensorflow as tf

# Point 1
x1 = tf.constant(2, dtype=tf.float32)
y1 = tf.constant(9, dtype=tf.float32)
point1 = tf.stack([x1, y1])

# Point 2
x2 = tf.constant(-1, dtype=tf.float32)
y2 = tf.constant(3, dtype=tf.float32)
point2 = tf.stack([x2, y2])

# Combine points into an array
X = tf.transpose(tf.stack([point1, point2]))
B = tf.ones((1, 2), dtype=tf.float32)

parameters = tf.matmul(B, tf.matrix_inverse(X))

with tf.Session() as session:
    A = session.run(parameters)
    b = 1 / A[0][1]
    a = -b * A[0][0]
    print("Equation: y = {a}x + {b}".format(a=a, b=b))
     writer = tf.summary.FileWriter("/tmp/tboard/output_HW_2",sect.graph)
    writer.close()


Equation: y = 2.0x + 5.000000298023242
