In [74]:


##Read 2 arrays x,y containing floating point values
    #importing the tensor flow and numpy
import tensorflow as tf
import numpy as np

arrX= [12.4 , 13.5 , 18.7 , 12.8]
x = tf.constant(arrX)
sect=tf.Session()
print(sect.run(x))

y = tf.constant([18.8 , 12.4 , 20.5 , 29.9])
sect=tf.Session()
print(sect.run(y))

m1,v1 = tf.nn.moments(x, axes=[0])
with tf.Session() as sect:
    m1=sect.run(m1)
    v1=sect.run(v1)
    print("mean is:",m1)
    print("varience:",v1)
    

[ 12.39999962  13.5         18.70000076  12.80000019]
[ 18.79999924  12.39999962  20.5         29.89999962]
mean is: 14.35
varience: 6.4625


In [75]:
m2,v2 = tf.nn.moments(y, axes=[0])
with tf.Session() as sect:
    m2=sect.run(m2)
    v2=sect.run(v2)
    print("mean is:",m2)
    print("varience:",v2)
    

mean is: 20.4
varience: 39.205


In [76]:
xi=tf.subtract(x,m1)
with tf.Session() as sect:
    ot=sect.run(xi)
    print(ot)

[-1.95000076 -0.85000038  4.35000038 -1.55000019]


In [77]:
yi=tf.subtract(y,m1)
with tf.Session() as sect:
    opt=sect.run(yi)
    print(opt)

[  4.44999886  -1.95000076   6.14999962  15.54999924]


In [78]:
p=tf.multiply(ot,opt)
n=len(arrX)
print(n)
with tf.Session() as sect:
    prod=sect.run(p)
    print(prod)
    

4
[ -8.67750072   1.65750134  26.75250053 -24.10250092]


In [79]:
sm=tf.reduce_sum(prod)
covar=tf.divide(sm,n)
with tf.Session() as sect:
    covarience=sect.run(covar)
    print("covar is:",covarience)
    

covar is: -1.0925


In [80]:
##m=covariance(x,y)/variance(x)
m = tf.div(covarience,v1)
with tf.Session() as sect:
    M=sect.run(m)
    print(M)

-0.169052


In [81]:
##c=mean(y)−m∗mean(x)
c1=tf.multiply(M,m1)
c=tf.subtract(m2,c1)
with tf.Session() as sect:
    C=sect.run(c)
    print(C)

22.8259
